import React from "react";

export interface IBlock {
  row?: boolean;
  column?: boolean;
  center?: boolean;
  children?: React.ReactNode;

  // Positioning and Spacing
  top?: number;
  end?: number;
  left?: number;
  right?: number;
  start?: number;
  bottom?: number;
  gap?: number | string;
  zIndex?: number;

  // Margin and Padding
  margin?: string | number;
  marginTop?: number;
  marginLeft?: number;
  marginRight?: number;
  marginBottom?: number;
  marginVertical?: number;
  marginHorizontal?: number;

  padding?: number;
  paddingTop?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingVertical?: number;
  paddingHorizontal?: number;
  // Styling
  style?: React.CSSProperties;
  width?: number;
  height?: number;
  radius?: number;
  align?: "start" | "end" | "center" | "space-between" | "space-around";
  justify?: "start" | "end" | "center" | "space-between" | "space-around";
  flex?: string | number;
  position?: "absolute" | "relative" | "fixed" | "static" | "sticky";
  overflow?: "visible" | "hidden" | "scroll" | "auto";
  transition?: string;

  // Colors and Appearance
  color?: string;
  borderColor?: string;
  shadow?: string;
  intensity?: string;
  border?: string;
  gray?: string;
  info?: string;
  wrap?: string;
  blur?: string;
  tint?: string;
  black?: string;
  white?: boolean;
  primary?: string;
  secondary?: string;
  tertiary?: string;
  warning?: string;
  danger?: string;
  success?: string;
  outlined?: string;
  scroll?: string;
}

export interface IText {
  [x: string]: any;
  id?: "Text";
  children?: JSX.Element;
  style?: React.CSSProperties;
  center?: boolean;
  gradient?: string;
  color?: string;
  opacity?: number;
  primary?: string;
  secondary?: string;
  tertiary?: string;
  black?: string;
  white?: boolean;
  gray?: string;
  danger?: string;
  warning?: string;
  success?: string;
  info?: string;
  size?: string;
  bold?: string;
  semibold?: string;
  weight?: string;
  h1?: string;
  h2?: string;
  h3?: string;
  h4?: string;
  h5?: string;
  h6?: string;
  p?: string;
  font?: string;
  align?: string;
  transform?: string;
  lineHeight?: string;
  position?: string;
  right?: number;
  left?: number;
  top?: number;
  bottom?: number;
  start?: number;
  end?: number;
  marginBottom?: number;
  marginTop?: number;
  marginHorizontal?: number;
  marginVertical?: number;
  marginRight?: number;
  marginLeft?: number;
  paddingBottom?: number;
  paddingTop?: number;
  paddingHorizontal?: number;
  paddingVertical?: number;
  paddingRight?: number;
  paddingLeft?: number;
}

export interface IButton {
  id?: "button";
  className?: string;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
  children?: React.ReactNode;
  navigation?: string;
  style?: any;
  shadow?: boolean;
  card?: string;
  center?: boolean;
  outlined?: string;
  overflow?: string;
  row?: string | number;
  safe?: string;
  keyboard?: string;
  scroll?: string;
  color?: string;
  gradient?: string;
  primary?: string;
  secondary?: string;
  tertiary?: string;
  black?: string;
  white?: boolean;
  gray?: string;
  danger?: string;
  warning?: string;
  success?: string;
  info?: string;
  radius?: string | number;
  height?: number | string;
  width?: number;
  margin?: number;
  marginBottom?: number;
  marginTop?: number;
  marginHorizontal?: number;
  marginVertical?: number;
  marginRight?: number;
  marginLeft?: number;
  padding?: number;
  paddingBottom?: number;
  paddingTop?: number;
  paddingHorizontal?: number;
  paddingVertical?: number;
  paddingRight?: number;
  paddingLeft?: number;
  justify?: string;
  align?: string;
  flex?: number;
  wrap?: string;
  blur?: string;
  intensity?: string;
  tint?: string;
  position?: string;
  disable?: string;
  right?: number;
  left?: number;
  top?: number;
  bottom?: number;
  end?: number;
  start?: number;
  neumorphism?: string;
}
