import React, { FC, forwardRef, memo, Ref } from "react";
import { TBlockProps } from "../types/components";
import { useTheme } from "../assets/theme";

const Block: FC<TBlockProps> = forwardRef<HTMLDivElement, TBlockProps>((props: TBlockProps, ref: Ref<HTMLDivElement>) => {
	const {
		row,
		top,
		end,
		grey,
		info,
		wrap,
		blur,
		tint,
		left,
		style,
		color,
		black,
		white,
		width,
		align,
		right,
		start,
		shadow,
		card,
		center,
		scroll,
		error,
		radius,
		height,
		margin,
		bottom,
		border,
		primary,
		warning,
		success,
		padding,
		justify,
		children,
		outlined,
		overflow,
		flex,
		position,
		secondary,
		marginTop,
		intensity,
		marginLeft,
		paddingTop,
		marginRight,
		paddingLeft,
		borderColor,
		marginBottom,
		paddingRight,
		paddingBottom,
		marginVertical,
		paddingVertical,
		marginHorizontal,
		paddingHorizontal,
		borderTop,
		borderLeft,
		borderRight,
		borderBottom,
		column,
		transition,
		gap,
		zIndex,
		bgColor,
		inlineFlex,
		flexShrink,
		opacity,
		cursor,
		alignSelf,
		transform,
		scrollX,
		scrollY,
		background,
		transparency,
		secGrad,
		priGrad,
		dropShadowLarge,
		dropShadowSmall,
		innerShadow,
		...rest
	} = props;
	const { colors, boxShadows, borders } = useTheme();

	const colorIndex = primary ? "primary" : secondary ? "secondary" : info ? "info" : success ? "success" : warning ? "warning" : white ? "white" : "";

	const blockColor = colorIndex && (color || colors?.[colorIndex].main);
	const blockStyles = {
		...style,
		...(flex && { display: "flex" }),
		...(inlineFlex && { display: "inline-flex" }),
		...(flexShrink && { flexShrink: flexShrink }),
		...(border && { border: border }),
		...(borderColor && { borderColor }),
		...(color && { color }),
		...(margin !== undefined && { margin }),
		...(marginBottom && { marginBottom }),
		...(marginTop && { marginTop }),
		...(marginHorizontal && { marginHorizontal }),
		...(marginVertical && { marginVertical }),
		...(marginRight && { marginRight }),
		...(marginLeft && { marginLeft }),
		...(padding !== undefined && { padding }),
		...(paddingBottom && { paddingBottom }),
		...(paddingTop && { paddingTop }),
		...(paddingHorizontal && { paddingHorizontal }),
		...(marginBottom && { marginBottom }),
		...(paddingVertical && { paddingVertical }),
		...(paddingRight && { paddingRight }),
		...(paddingLeft && { paddingLeft }),
		...(radius && { borderRadius: radius }),
		...(height && { height }),
		...(width && { width }),
		...(overflow && { overflow }),
		...(row && { flexDirection: "row" }),
		...(column && { flexDirection: "column" }),
		...(gap && { gap: gap }),
		...(align && { alignItems: align }),
		...(center && { justifyContent: "center" }),
		...(justify && { justifyContent: justify }),
		...(wrap && { flexWrap: wrap }),
		...(scroll && { overflow: "scroll" }),
		...(blur && { backdropFilter: `blur(${blur}px)` }),
		...(tint && { WebkitBackdropFilter: `blur(${blur}px)`, backdropFilter: `blur(${blur}px)` }),
		...(intensity && { WebkitBackdropFilter: `brightness(${intensity}%)` }),
		...(transition && { transition: transition }),
		...(outlined && { borderWidth: 1, backgroundColor: "transparent" }),
		...(blockColor && { backgroundColor: blockColor }),
		...(black && { backgroundColor: colors.black.main }),
		...(white && { backgroundColor: colors.white.main }),
		...(info && { backgroundColor: colors.info.main }),
		...(success && { backgroundColor: colors.success.main }),
		...(warning && { backgroundColor: colors.warning.main }),
		...(primary && { backgroundColor: colors.primary.main }),
		...(secondary && { backgroundColor: colors.secondary.main }),
		...(bgColor && { backgroundColor: bgColor }),
		...(end && { alignSelf: "flex-end" }),
		...(start && { alignSelf: "flex-start" }),
		...(shadow && { boxShadow: boxShadows.cardShadow.main }),
		...(position && { position }),
		...(zIndex && { zIndex }),
		...(right !== undefined && { right }),
		...(left !== undefined && { left }),
		...(top !== undefined && { top }),
		...(bottom !== undefined && { bottom }),
		...(grey && { backgroundColor: colors.grey[100] }),
		...(error && { backgroundColor: colors.error.main }),
		...(card && { backgroundColor: colors.white.main, borderRadius: borders.borderRadius.card, boxShadow: boxShadows.cardShadow.main }),
		...(cursor && { cursor: "pointer" }),
		...(opacity && { opacity }),
		...(alignSelf && { alignSelf }),
		...(transform && { transform }),
		...(scrollX && { overflowX: "scroll" }),
		...(scrollY && { overflowY: "scroll" }),
		...(borderTop && { borderTop }),
		...(borderLeft && { borderLeft }),
		...(borderRight && { borderRight }),
		...(borderBottom && { borderBottom }),
		...(background && { backgroundColor: colors.background.default }),
		...(transparency && { backgroundColor: colors.white.transparency }),
		...(secGrad && { background: colors.gradients.secondary.main }),
		...(priGrad && { background: colors.gradients.primary.main }),
		...(dropShadowLarge && { boxShadow: boxShadows.dropShadowLarge.main }),
		...(dropShadowSmall && { boxShadow: boxShadows.dropShadowSmall.main }),
		...(innerShadow && { boxShadow: boxShadows.innerShadow.main }),
	} as React.CSSProperties;
	return (
		<div ref={ref} style={{ ...blockStyles }} {...rest}>
			{children}
		</div>
	);
});

export default memo(Block);
