name: Build and Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
          sudo apt-get update
          sudo apt-get install --install-recommends winehq-stable
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0
      - name: Install dependencies
        run: npm install
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_ENV: production
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            npm run deploy
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            npm run deploy-beta
          fi
