name: Build and Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Update package list
        run: sudo apt-get update
      - name: Install wine-stable
        run: sudo apt-get install -y wine-stable
      - name: Fix broken dependencies
        run: sudo apt-get install -f
      - name: Install dependencies
        run: npm ci
      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            npm run deploy
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            npm run deploy-beta
          fi
